### ISSUE TITLE
Small unnoticeable issue in the cpp file.

### ISSUE THREAD

**Issue by kawkawa-codes** [GarvitSinghh/Donuts#12]
line 14, instead of:  cout<<"\x1b[2J"; it should be modified to cout<<"\x1b[23m";

As i guess you went with the C version of white foreground, which will make your terminal unable to execute your code. Overall very interesting code :)

**Comment by GarvitSinghh** [comment]
The purpose of \x1b[2J is to clear the entire terminal screen. Could you please elaborate on what you mean by saying that it will make the terminal unable to execute the code?
